spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver


dishbrary:
  init:
    security: true
    ingredients: true
    cuisines: true
    categories: true
  ingredients:
    images:
      default:
        name: default.png
  cuisine:
    images:
      default:
        name: default.png
  resources:
    imageBasePathByComponentName:
      cuisine: /home/znato/work/szakdolgozat/dishbrary/cuisine_icons/
      ingredient: /path/to/ingredientImages/